_format_version: "2.1"
_transform: true

services:
  - name: example-service
    url: http://localhost:1026/v2/entites
    plugins:
      - name: multi-tenancy, rbac, scope-checker, query-checker, oidc